version: '3.8'

services:
  director:
    build:
      context: .
      dockerfile: director/Dockerfile
    container_name: director
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    tty: true

  doshbank:
    build:
      context: .
      dockerfile: doshbank/Dockerfile
    container_name: doshbank
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    tty: true

  datanode1:
    build:
      context: .
      dockerfile: datanode/Dockerfile
    container_name: datanode1
    ports:
      - "8071:8071"
    networks:
      - mynetwork
    command: ["/server","1"]
    tty: true

  datanode2:
    build:
      context: .
      dockerfile: datanode/Dockerfile
    container_name: datanode2
    ports:
      - "8072:8072"
    networks:
      - mynetwork
    command: ["/server","2"]
    tty: true

  datanode3:
    build:
      context: .
      dockerfile: datanode/Dockerfile
    container_name: datanode3
    ports:
      - "8073:8073"
    networks:
      - mynetwork
    command: ["/server","3"]
    tty: true

  namenode:
    build:
      context: .
      dockerfile: namenode/Dockerfile
    container_name: namenode
    ports:
      - "8070:8070"
    networks:
      - mynetwork
    tty: true

networks:
  mynetwork:
    driver: bridge
