version: '3.8'

services:
  director:
    build:
      context: .
      dockerfile: director/Dockerfile
    container_name: director
    ports:
      - '${DIRECTOR_PORT}:${DIRECTOR_PORT}'
    env_file:
      - .env
    networks:
      - mynetwork

  doshbank:
    build:
      context: .
      dockerfile: doshbank/Dockerfile
    container_name: doshbank
    ports:
      - '${DOSHBANK_PORT}:${DOSHBANK_PORT}'
    env_file:
      - .env
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
