FROM golang:1.22

WORKDIR /app

COPY . .

RUN go mod tidy

RUN go build -o centrals ./centrals/main.go
RUN go build -o pirates ./pirates/main.go

RUN chmod +x centrals/main
RUN chmod +x pirates/main

CMD ./centrals/main & ./pirates/main
